name: abhishek_doshi_portfolio
description: Abhishek Doshi portfolio website.

publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.2
  dots_indicator: ^3.0.0
  feather_icons: ^1.1.0-nullsafety.0
  firebase_analytics: ^10.4.4
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.0
  font_awesome_flutter: ^10.5.0
  go_router: ^13.2.4
  google_fonts: ^6.1.0
  layout: ^1.0.5
  responsive_builder: ^0.7.0
  url_launcher: ^6.0.3
  url_strategy: ^0.2.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
