name: abhishek_doshi_portfolio
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.1
  auto_route: ^3.2.2
  auto_route_generator: ^3.2.1
  auto_size_text: ^3.0.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dots_indicator: ^2.0.0
  feather_icons: ^1.1.0-nullsafety.0
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.0
  font_awesome_flutter: ^9.0.0-nullsafety
  google_fonts: ^5.1.0
  layout: ^0.6.2
  responsive_builder: ^0.4.1
  url_launcher: ^6.0.3
  visibility_detector: ^0.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/
